### ISSUE TITLE
Alarm always triggered

### ISSUE THREAD

**Issue by adekka** [grover/homebridge-automation-switches#1]
I love the easiness of your plugin. I just can't figger out how the 'arm' and 'triggered' modus work.

I've installed multiple motion sensors which I want to use as triggers when I put the security system in 'armed' modus. But when I set the modus on 'armed' I always get notified that the system has been triggered. 

What should I do to get the motion sensors work as triggers when the system is armed.

**Comment by grover** [comment]
I'm not sure I understand the issue, could you please post the exact rules and scenes, what you expect to happen and what you experience?

**Comment by adekka** [comment]
My rules:
if motion is detected
and alarm is set to armed
set lights to red

this works fine. 

However, what the Eve app show me when I arm the system is: system is triggered (red light symbol). How is the system triggered? Or is this the standard value when you arm the system?

**Comment by grover** [comment]
There's two rows of buttons in Eve:

![](https://github.com/grover/homebridge-automation-switches/blob/master/docs/SecuritySystem.png?raw=true)

The top row indicates the mode of the alarm system, e.g. stay - you're at home, but the system is on. away: The system is on, but you're not at home, night: the system is armed during the night.

The button below it is actually triggering the alarm, e.g. it'll send you a notification to your devices that the alarm system was triggered.

Your rules should thus be:

if motion is detected
and state is not disarmed
set lights to red
and set alarm to on

**Comment by adekka** [comment]
ahhh.. thanks! Now I understand!

**Comment by vsidlu** [comment]
is there a way to trigger alarm in home app? i can only change state in home app. also rules do not offer alarm triggering. in eve i see alarm and can trigger it.

i know that if i want to get picture from camera if there is motion - i need to put camera and motion sensor in one room (home app). but there it is not helping :( 

what i am missing?
