### ISSUE TITLE
Zones for clock switch

### ISSUE THREAD

**Issue by Nastras** [grover/homebridge-automation-switches#10]
Hello grover,

It would be possible for the alarm clock switch zones to provide as in the security switch?

**Comment by grover** [comment]
Hey,

can you give an explanation how you'd use this? It would help me to update the documentation.

Thanks,
Michael

**Comment by Nastras** [comment]
Hey grover,
the zones should serve as conditions for various alarm clocks with one switch.

Example:
Alarm clock only wake up if the zone bedroom is activated in addition to the activation switch.

If I want to wake up in the living room at lunchtime, I activate the zone living room as a condition and the activation switch for the alarm clock. Now the alarm clock wakes up in the living room.

I hope you can understand it?

Greeting Nastra

**Comment by Nastras** [comment]
@grover Too bad they don't hear from you anymore. We would be happy if you visit the SmartApfel Forum again.

Greetings Nastra
