### ISSUE TITLE
Error automation switch cannot add bridged accessory uuid already used - more than one switch

### ISSUE THREAD

**Issue by BAngel87** [grover/homebridge-automation-switches#12]
Hello,

I try to add different automations switches. My config loocks like the following:

`"switches" : [
{
"period" : "1800",
"name" : "Schlafzimmerlicht",
"type" : "automation",
"autoOff" : "false"
},
{
          "type": "switch",
          "name": "VS_Frühmorgen",
          "stored": true,
          "default": false
},
{
          "type": "switch",
          "name": "VS_Morgen",
          "stored": true,
          "default": false
},
{
          "type": "switch",
          "name": "VS_Morgen",
          "stored": true,
          "default": false
},
{
          "type": "switch",
          "name": "VS_Mittag",
          "stored": true,
          "default": false
},
{
          "type": "switch",
          "name": "VS_Sonnenuntergang",
          "stored": true,
          "default": false
},
{
          "type": "switch",
          "name": "VS_Abend",
          "stored": true,
          "default": false
},
{
          "type": "switch",
          "name": "VS_Nacht",
          "stored": true,
          "default": false
},
{
          "type": "switch",
          "name": "VS_Filmlicht",
          "stored": true,
          "default": false
},
{
          "type": "switch",
          "name": "VS_Sonnentag",
          "stored": true,
          "default": false
}
],
"platform" : "AutomationSwitches",
"name" : "device"
},`

Sadly then Homebridge isn't starting anymore and I get the Error:

"Cannot add bridged Accessory with the same UUID as another brdiged Accessory"

Is there a mistake in my config jason creating more than one switch? 

Thanks for your support,...

**Comment by grover** [comment]
You had two switches with the same name in the configuration :( (VS_Morgen)
