### ISSUE TITLE
accessories blocked after installing homebridge-automation-switches

### ISSUE THREAD

**Issue by jngothia** [grover/homebridge-automation-switches#2]
Hi there, I thought your homebridge-automation-platform switches looked like it might make for good addition to my Home, so I downloaded it, added the necessary stuff into my config (I chose three things: a security item, an automation item, and a lock item).  When I fired up the instance of homebridge and went to the Home app in my iPhone, every accessory became unresponsive.  In the Eve app, it notes each unresponsive accessory has been "blocked."  It appears that the only way around it afterwards is to delete the home and the accessories & persist folder, revert my config.json, and re-add the home from scratch.  

Just wondering if you might have any suggestions for this.  It crossed my mind that maybe Apple had increased security and is "blocking" accessories in the wake of the Intel Meltdown issues in such a manner as to make everything stop working if I try to add stuff like your platform.  

Thanks,
Jacob

**Edit:**

I was able to add your platform successfully after removing the "security" accessory and the "lock" accessory, and keeping just the "automation" accessory, so perhaps there is something about the presence of one or both of those accessories that may be causing the issue, either on my end or maybe Apple doesn't approve of these items for some reason?

**Comment by grover** [comment]
Hey Jacob,

I can only say that at the moment it works for me on various iOS devices with iOS 11.2.1.

Can you give me an example config.json that breaks? What iOS version are you on?

Thanks!

**Comment by jngothia** [comment]
Hi Grover, thanks for responding.  I'm running iOS 11.2.2.  

Below is the relevant section of the config.json that has been giving me problems.  When I added to my current setup, every accessory was immediately blocked.  When I deleted the home, starting everything over from scratch, and tried to add the Homebridge in the iOS Home app, it responded that Homebridge can't be added.  But it works when I only have the "automation" type switch in my config.json.  

    "platforms": [
      {
      "platform": "AutomationSwitches",
      "switches":
      [
        {
          "type": "automation",
          "name": "Departure Switch",
          "period": 120,
          "autoOff": true,
          "default": false,
          "stored": false
        },{
          "type": "lock",
          "name": "Lock Simulator",
          "default": "locked",
          "stored": true
        },{
          "type": "security",
          "name": "Security System Simulator",
          "default": "armed-stay",
          "stored": false
        }
      ]
    },

I'll probably try to set it up with just the automation type switch for now, as I'm not certain how I would have used the lock and security system type switches yet anyway--the automation type switch was the one I really wanted and it looks like I can get it to work. 

Thanks again,
Jacob

**Comment by grover** [comment]
I've now run this with various other plugins in combination and various iOS versions. I don't experience the issues you're reporting. If this still occurs for you, please reopen and submit:

- The homebridge log file
- A list of plugins you're using
- The current config

Thanks!
