### ISSUE TITLE
Trigger Alarm

### ISSUE THREAD

**Issue by jorgdeboer** [grover/homebridge-automation-switches#25]
I’m probably missing something. But how do I trigger the Alarm? I can set it to different states, but I’m not able to actually trigger the alarm. 

In the eve app I only can set the different states (home, away, night, disarmed) as an action, but not Alarm triggered or something. 

Thanks.

**Comment by paolotremadio** [comment]
Hi. Can you please post your config? Also: have you set any zones?

**Comment by jorgdeboer** [comment]
No I haven’t set any zones. Just the example config:

 {
            "platform": "AutomationSwitches",
            "switches": [
                {
                    "type": "automation",
                    "name": "Automation Switch #1",
                    "period": 1800,
                    "autoOff": false
                },
                {
                    "type": "security",
                    "name": "Home alarm"
                }
            ]
        }

**Comment by paolotremadio** [comment]
Add some zones, see https://github.com/grover/homebridge-automation-switches/blob/master/docs/SecuritySystem.md

The plugin will expose a switch for each zone. Turning on any of the switch will trigger the alarm :)

**Comment by jorgdeboer** [comment]
Thanks, I’ll try that tonight and let’s see if that works :)

**Comment by paolotremadio** [comment]
You're welcome 😊  feel free to close the issue
