### ISSUE TITLE
Add a configurable slider to the supported switches

### ISSUE THREAD

**Issue by grover** [grover/homebridge-automation-switches#3]
- Add a slider with configurable min, max, step and valid values.
- Should be readable, writeable and notify. 
- Should make use of an existing HomeKit characteristic to enable integration with Home

**Comment by vrachamis** [comment]
Could you please preview an example of a Config.json entry for the slider you mentioned?

**Comment by grover** [comment]
The slider documentation is at: https://github.com/grover/homebridge-automation-switches/blob/master/docs/Slider.md

**Comment by vrachamis** [comment]
Thank you, but there is no "Step" field in the Config.json example entry.

**Comment by grover** [comment]
That's because I didn't add it yet.

**Comment by vrachamis** [comment]
Oh, i see. Thank you for your attention. 
Your plugin is very useful indeed. :)

**Comment by grover** [comment]
@vrachamis I've added the minStep support in release 3.2.0, which has just gone live. I've also updated the documentation and the slider example.

**Comment by vrachamis** [comment]
Thank you very very much! I really owe you! keep up the good work.
