### ISSUE TITLE
homekit alarm triggering

### ISSUE THREAD

**Issue by vsidlu** [grover/homebridge-automation-switches#5]
is there a way to trigger alarm in home app? i can only change state in home app. also rules do not offer alarm triggering. in eve i see alarm and can trigger it.

what i am missing?

thanks for help in advance!

**Comment by grover** [comment]
You’re not missing anything. Trigger characteristic is not yet supported in Home.

**Comment by vsidlu** [comment]
thanks for info and plugin!
