### ISSUE TITLE
Security System - night mode issue

### ISSUE THREAD

**Issue by vrachamis** [grover/homebridge-automation-switches#7]
Hello grover,
I took advantage of your Security system combining my 4 Hue motion sensors but I have an issue with the night mode state.
Let's say I'm running on "stay" mode. When I decide to switch to "away" mode (manually or automatically), then the "stay" switch automatically turns Off, the "away" switch turns On and the main security switch that is triggering an alarm successfully updates its status to "away" and vice versa.
But when I toggle between "Night' mode and any other mode (away or stay), the night switch always stays On and never turns Off, although the main security switch successfully updates its status to the latest one.
This Happens of course on both Home & Elgato app. All apps are up to date on an iOS 11.2.2 iDevice

Any help would be appreciated.

**Comment by grover** [comment]
Should be solved with the 3.2.1 release today.

**Comment by vrachamis** [comment]
Works like a charm! Thanks again.
